# Generated by Django 5.0.2 on 2025-03-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0003_alter_accommodation_meal_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='meal_option',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
