# Generated by Django 5.0.2 on 2025-03-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0005_alter_accommodation_meal_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='meal_option',
            field=models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner'), ('A', 'All')], default='A', max_length=10),
        ),
    ]
